<a href="https://colab.research.google.com/github/sandeepasandy/Data-Analytics-Practice/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [ ]:
!pip install pandas

Requirement already satisfied: panda in /usr/local/lib/python3.12/dist-packages (0.3.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from panda) (75.2.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from panda) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->panda) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->panda) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->panda) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->panda) (2026.6.17)

In [ ]:
#importing pandas
import pandas as pd
print("pandas imported")

pandas imported

In [ ]:
#creating series
data = [1,2,3,4]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
data = [1,2,3,4]
i= ['a','b','c','d']
s = pd.Series(data,index=i)
print(s)
#updating
s['a']=10
print(s)
s["c"] = 30
print(s)
#inserting new data(directly,concat)
s["f"] = 80
print(s)
#remove(drop method)
s = s.drop("a")
print(s)

a    1
b    2
c    3
d    4
dtype: int64
a    10
b     2
c     3
d     4
dtype: int64
a    10
b     2
c    30
d     4
dtype: int64
a    10
b     2
c    30
d     4
f    80
dtype: int64
b     2
c    30
d     4
f    80
dtype: int64

In [ ]:
#creating a series from dictionary
s2 = pd.Series({'x':100, 'y':200, 'z':300})
print(s2)

x    100
y    200
z    300
dtype: int64

In [ ]:
#accessing
print(s2[0])
print(s2[0:2])
print(s2[1:])
print(s2[:2])

100
x    100
y    200
dtype: int64
y    200
z    300
dtype: int64
x    100
y    200
dtype: int64

/tmp/ipykernel_1561/2449115560.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[0])

In [ ]:
import pandas as pd
data = [78,85,92,67,88]
roll = [101,102,103,104,105]
s = pd.Series(data,index=roll)
print(s)
print(s[103])
s[104]=75
print(s)
s= s.drop(102)
print(s)
s[106]=90
print(s)

101    78
102    85
103    92
104    67
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    90
dtype: int64

In [ ]:
#Viewing:
import pandas as pd
s = pd.Series(
        [5000,7000,6000,9000,8000],
index = ["Monday","Tuesday","wednesday","Thursday","Friday"]
)
print(s)
print(s.head(4))#return the first five elements
print(s.tail())#return the last five elements
print(len(s))#return the length of the elements
print(s.shape)#return the number of rows and coloumns
print(s.index)#index positions
s.values#gets all the values
s["Monday"]
s[["Monday","wednesday"]]
s > 6000
s[s > 6000]

Monday       5000
Tuesday      7000
wednesday    6000
Thursday     9000
Friday       8000
dtype: int64
Monday       5000
Tuesday      7000
wednesday    6000
Thursday     9000
dtype: int64
Monday       5000
Tuesday      7000
wednesday    6000
Thursday     9000
Friday       8000
dtype: int64
5
(5,)
Index(['Monday', 'Tuesday', 'wednesday', 'Thursday', 'Friday'], dtype='object')

Tuesday     7000
Thursday    9000
Friday      8000
dtype: int64

In [ ]:
#cleaning data
#missing values
s = pd.Series([5000,7000,None,9000,None])
print(s)
s.isna()

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
import pandas as pd
s = pd.Series(
    [5000,7000,6000,9000,8000],
    index=["Monday","Tuesday","Wednesday","Thursday","friday"]
)

s.iloc[0:3]#prints the index value
s.loc["Monday"]

np.int64(5000)

In [ ]:
import pandas as pd
data = {
    "Name":["Ravi","priya","Arjun","shalini","Satya"],
    "Age" :[22,25,None,24,None],
    "City":["Hyderabad","Vizag","Srikakulam","kakinada","Delhi"],
    "Salary":[30000,40000,25000,30000,50000]
}
i = [101,102,103,104,105]

df = pd.DataFrame(data,index = i)
print(df)
df.iloc[0:3]#gives the index values upto 3
df.loc[101]
df.loc[101:103]

        Name   Age        City  Salary
101     Ravi  22.0   Hyderabad   30000
102    priya  25.0       Vizag   40000
103    Arjun   NaN  Srikakulam   25000
104  shalini  24.0    kakinada   30000
105    Satya   NaN       Delhi   50000

      Name   Age        City  Salary
101   Ravi  22.0   Hyderabad   30000
102  priya  25.0       Vizag   40000
103  Arjun   NaN  Srikakulam   25000

In [ ]:
#Aggregation functions
import pandas as pd
s = pd.Series(
    [5000,7000,6000,9000,8000],
    index=["Monday","Tuesday","Wednesday","Thursday","friday"]
)
s.min()
s.max()
s.count()
s.mean()
s.median()
s.std()
s.sum()

<bound method Series.max of Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
friday       8000
dtype: int64>

In [ ]:
import pandas as pd
data = {
    "Name":["Ravi","priya","Arjun","shalini","Satya"],
    "Age" :[22,25,None,24,None],
    "City":["Hyderabad","Vizag","Srikakulam","kakinada","Delhi"],
    "Salary":[30000,40000,25000,30000,50000]
}
df.min()
df.max()
df.count()

Name      5
Age       3
City      5
Salary    5
dtype: int64

In [ ]:
#concat:It is the method to combine the series
#ignore_index=True:It is used rearranging the index while combining the series
s1 = pd.Series([100,200,300])
s2 = pd.Series([400,500,600])
print(s1)
print(s2)
r = pd.concat([s1,s2],ignore_index=True)
print(r)
#merge does not work on series it works on dataframes

0    100
1    200
2    300
dtype: int64
0    400
1    500
2    600
dtype: int64
0    100
1    200
2    300
3    400
4    500
5    600
dtype: int64

In [ ]:
import pandas as pd
data = [25000,28000,32000,None,35000,38000,None,42000,45000,48000]
i= ['01-Aug','02-Aug','03-Aug','04-Aug','05-Aug','06-Aug','07-Aug','08-Aug','09-Aug','10-Aug']
s = pd.Series(data,index=i)
print(s)
s.head((5))
s.tail((3))
s.isna()
s.fillna(s.mean())#replacing missing values with average sales
s>35000
s.drop('04-Aug')
s.count()
s.replace(32000,34000)
s.min()
s.max()
s.mean()
s.median()

01-Aug    25000.0
02-Aug    28000.0
03-Aug    32000.0
04-Aug        NaN
05-Aug    35000.0
06-Aug    38000.0
07-Aug        NaN
08-Aug    42000.0
09-Aug    45000.0
10-Aug    48000.0
dtype: float64

36500.0

In [ ]:
import pandas as pd
Month = ['January','February','March','April','May','June','july','August','September','October']
i = [120000,135000,None,150000,165000,None,180000,195000,210000,225000]
s = pd.Series(i, index=Month)
print(s)
s.head((5))
s.tail((3))
print(s[['January','March','May']])
print(s[s > 170000])
print(s.isnull())
print(s.isnull().sum())
s = s.fillna(s.mean())
s['April'] = 155000
print(s)
s = s.drop('February')
print(s)
s['November'] = 240000
print(s)
print(s.sum())
print(s.mean())
print(s.max())
print(s.min())
December = pd.Series([250000], index=['December'])
s = pd.concat([s, December])
print(s)

January      120000.0
February     135000.0
March             NaN
April        150000.0
May          165000.0
June              NaN
july         180000.0
August       195000.0
September    210000.0
October      225000.0
dtype: float64
January    120000.0
March           NaN
May        165000.0
dtype: float64
july         180000.0
August       195000.0
September    210000.0
October      225000.0
dtype: float64
January      False
February     False
March         True
April        False
May          False
June          True
july         False
August       False
September    False
October      False
dtype: bool
2
January      120000.0
February     135000.0
March        172500.0
April        155000.0
May          165000.0
June         172500.0
july         180000.0
August       195000.0
September    210000.0
October      225000.0
dtype: float64
January      120000.0
March        172500.0
April        155000.0
May          165000.0
June         172500.0
july         180000.0
August       195000.0
September    210000.0
October      225000.0
dtype: float64
January      120000.0
March        172500.0
April        155000.0
May          165000.0
June         172500.0
july         180000.0
August       195000.0
September    210000.0
October      225000.0
November     240000.0
dtype: float64
1835000.0
183500.0
240000.0
120000.0
January      120000.0
March        172500.0
April        155000.0
May          165000.0
June         172500.0
july         180000.0
August       195000.0
September    210000.0
October      225000.0
November     240000.0
December     250000.0
dtype: float64

In [ ]:
import pandas as pd #combining two or more series in a dataframe
s = pd.Series(
    [1,2,3,4],
    name = 'Numbers'
)
s2 =pd.Series([9,6,5,4])
s3 =pd.Series([15,14,16,14])

df = s.to_frame()
print(df)
d = {
"name" :s,
"age"  :21,
"marks":50}
df = pd.DataFrame(d)
print(df)
df.columns = ['Digits']#renaming the single column
print(df)

   Numbers
0        1
1        2
2        3
3        4
   name  age  marks
0     1   21     50
1     2   21     50
2     3   21     50
3     4   21     50

In [ ]:
s = pd.Series(
    [1,2,3,4],
    name = 'Numbers'
)
df = s.to_frame()
df.columns = ['Digits']#renaming the single column
print(df)
#for renaming multiple columns we should use rename()

   Digits
0       1
1       2
2       3
3       4

In [ ]:
#for renaming multiple columns we should use rename()
d = {
"A" :s,
"B"  :21,
"marks":50}
df = pd.DataFrame(d)
print(df)
df.rename(
    columns={
        'A':'Alpha',
        'B':'Beta'
    },
    inplace = True

)

   A   B  marks
0  1  21     50
1  2  21     50
2  3  21     50
3  4  21     50

In [ ]:
import pandas as pd
data = {
    "Name": ["Raju", "Bunty", "Charli","sandy","prudhvi"],
    "Age": [25, 30, 35, 21, 22],
    "City": ["USA", "Hyderabad", "Punjab", "Vizag", "Vijayawada"]
}
df = pd.DataFrame(data)
print(df)
df.head(2)
df.tail(3)
df.info()#gives all the information about the dataframe
df.describe()#provides the information such as mean,min,max,count,standard deviation
df['Name']#selecting a single column
df[['Name','Age']]#selecting the multiple columns in single data frame by giving two lists
df.iloc[2]#selecting rows by using iloc method
df.loc[3]#selecting rows by using loc method

      Name  Age        City
0     Raju   25         USA
1    Bunty   30   Hyderabad
2   Charli   35      Punjab
3    sandy   21       Vizag
4  prudhvi   22  Vijayawada
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

Name    sandy
Age        21
City    Vizag
Name: 3, dtype: object

In [ ]:
#filtering
import pandas as pd
data = {
    "Name":["Ravi","priya","Arun","sneha","kiran","Anjali","Vikram","Meena"],
    "Age" :[22,24,None,25,None,26,20,27],
    "City":["Hyderabad","chennai","Bangalore","Hyderabad","Mumbai",None,"Bangalore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,None,55000]
}
df = pd.DataFrame(data)
print(df)
df.iloc[0:3]
df.loc[0]
print("___________________")#getting the members whose age is above 21 with the boolean values
e = df["Age"]>21
print(e)
print("___________________")
d = df[df["Age"]>21]
print(d)
print("___________________")#getting the salary whose salary is greater than 45000
s = df[df["Salary"]>45000]
print(s)
print("_________________")#getting the members whose age is greater than 22 and city is equal to Hyderabad
g = df[                      #by using and operator
    (df["Age"]>22) &
     (df["City"]=="Hyderabad")
]
print(g)
print("_________________")#getting the members whose salary is greater than 45000 and city is equal to mumbai
e = df[                   #with using or(|) operator
    (df["Salary"]>45000) |
    (df["City"]=="Mumbai")
]
print(e)
df.isna()
df.dropna(axis=0)#deletes the rows which have none values
df.dropna(how='all')
df.dropna(axis=0,inplace=True)#changes the  null values permantely
print(df)
df.fillna({
    'Age':0,
    'City':'Unknown'
})
print(df)

     Name   Age       City   Salary
0    Ravi  22.0  Hyderabad  30000.0
1   priya  24.0    chennai  40000.0
2    Arun   NaN  Bangalore  28000.0
3   sneha  25.0  Hyderabad  50000.0
4   kiran   NaN     Mumbai  35000.0
5  Anjali  26.0       None  45000.0
6  Vikram  20.0  Bangalore      NaN
7   Meena  27.0     Mumbai  55000.0
___________________
0     True
1     True
2    False
3     True
4    False
5     True
6    False
7     True
Name: Age, dtype: bool
___________________
     Name   Age       City   Salary
0    Ravi  22.0  Hyderabad  30000.0
1   priya  24.0    chennai  40000.0
3   sneha  25.0  Hyderabad  50000.0
5  Anjali  26.0       None  45000.0
7   Meena  27.0     Mumbai  55000.0
___________________
    Name   Age       City   Salary
3  sneha  25.0  Hyderabad  50000.0
7  Meena  27.0     Mumbai  55000.0
_________________
    Name   Age       City   Salary
3  sneha  25.0  Hyderabad  50000.0
_________________
    Name   Age       City   Salary
3  sneha  25.0  Hyderabad  50000.0
4  kiran   NaN     Mumbai  35000.0
7  Meena  27.0     Mumbai  55000.0
    Name   Age       City   Salary
0   Ravi  22.0  Hyderabad  30000.0
1  priya  24.0    chennai  40000.0
3  sneha  25.0  Hyderabad  50000.0
7  Meena  27.0     Mumbai  55000.0
    Name   Age       City   Salary
0   Ravi  22.0  Hyderabad  30000.0
1  priya  24.0    chennai  40000.0
3  sneha  25.0  Hyderabad  50000.0
7  Meena  27.0     Mumbai  55000.0

In [ ]:
df = pd.DataFrame(data)
df.fillna({
    'Age':0,
    'City':'Unknown'
})
print(df)
df['Age'] = df['Age'].fillna(#Gives the mean values of the null values
    df['Age'].mean())
print(df)
df['Salary'] =df['Salary'].fillna(
    df['Salary'].mean())
print(df)

     Name   Age       City   Salary
0    Ravi  22.0  Hyderabad  30000.0
1   priya  24.0    chennai  40000.0
2    Arun   NaN  Bangalore  28000.0
3   sneha  25.0  Hyderabad  50000.0
4   kiran   NaN     Mumbai  35000.0
5  Anjali  26.0       None  45000.0
6  Vikram  20.0  Bangalore      NaN
7   Meena  27.0     Mumbai  55000.0
     Name   Age       City   Salary
0    Ravi  22.0  Hyderabad  30000.0
1   priya  24.0    chennai  40000.0
2    Arun  24.0  Bangalore  28000.0
3   sneha  25.0  Hyderabad  50000.0
4   kiran  24.0     Mumbai  35000.0
5  Anjali  26.0       None  45000.0
6  Vikram  20.0  Bangalore      NaN
7   Meena  27.0     Mumbai  55000.0
     Name   Age       City        Salary
0    Ravi  22.0  Hyderabad  30000.000000
1   priya  24.0    chennai  40000.000000
2    Arun  24.0  Bangalore  28000.000000
3   sneha  25.0  Hyderabad  50000.000000
4   kiran  24.0     Mumbai  35000.000000
5  Anjali  26.0       None  45000.000000
6  Vikram  20.0  Bangalore  40428.571429
7   Meena  27.0     Mumbai  55000.000000

In [ ]:
import pandas as pd
emp_details ={
    "EmpID":[101,102,103,104,101],
    "City":["Hyderabad","Chennai","Bangalore",None,"Hyderabad"],
    "Experience":[None,4,3,5,2],
    "Age":[25,30,None,35,25]
}
df = pd.DataFrame(emp_details)
print(df)
df.isna()
df.isna().sum()
df.fillna({
    'Experience':0,
    'City':'Unknown'
})
df['Age'] = df['Age'].fillna(
    df['Age'].median())
print(df)
df.rename(
    columns={
        'EmpID':'Employee_id'
    }
)
df["Salary"]=[20000,35000,50000,1000,None]
print(df)
df["Age"] = df["Age"]+1#getting age of employee after one year-updating a column
print(df)
df["Bonus"]=df["Salary"]*0.10#getting bonus of every employeee
print(df)
df.drop(#drop can remove columns from a DataFrame
    'Age',
    axis=1,
    inplace=True,#it is used to delete permanantely
)
df.drop(#used to delete multiple columns
    columns=['Salary','Bonus'],
)
print("__________________________")
df.loc[len(df)]=[106,"Vizag",3,25,45000]#adding a new row
print(df)
df.drop(2,axis=0,inplace=True)#Deleting a row
print(df)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    101  Hyderabad         2.0  25.0
   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0  27.5
3    104       None         5.0  35.0
4    101  Hyderabad         2.0  25.0
   EmpID       City  Experience   Age   Salary
0    101  Hyderabad         NaN  25.0  20000.0
1    102    Chennai         4.0  30.0  35000.0
2    103  Bangalore         3.0  27.5  50000.0
3    104       None         5.0  35.0   1000.0
4    101  Hyderabad         2.0  25.0      NaN
   EmpID       City  Experience   Age   Salary
0    101  Hyderabad         NaN  26.0  20000.0
1    102    Chennai         4.0  31.0  35000.0
2    103  Bangalore         3.0  28.5  50000.0
3    104       None         5.0  36.0   1000.0
4    101  Hyderabad         2.0  26.0      NaN
   EmpID       City  Experience   Age   Salary   Bonus
0    101  Hyderabad         NaN  26.0  20000.0  2000.0
1    102    Chennai         4.0  31.0  35000.0  3500.0
2    103  Bangalore         3.0  28.5  50000.0  5000.0
3    104       None         5.0  36.0   1000.0   100.0
4    101  Hyderabad         2.0  26.0      NaN     NaN
__________________________
   EmpID       City  Experience   Salary    Bonus
0    101  Hyderabad         NaN  20000.0   2000.0
1    102    Chennai         4.0  35000.0   3500.0
2    103  Bangalore         3.0  50000.0   5000.0
3    104       None         5.0   1000.0    100.0
4    101  Hyderabad         2.0      NaN      NaN
5    106      Vizag         3.0     25.0  45000.0
   EmpID       City  Experience   Salary    Bonus
0    101  Hyderabad         NaN  20000.0   2000.0
1    102    Chennai         4.0  35000.0   3500.0
3    104       None         5.0   1000.0    100.0
4    101  Hyderabad         2.0      NaN      NaN
5    106      Vizag         3.0     25.0  45000.0

In [ ]:
import pandas as pd
emp_details ={
    "EmpID":[101,102,103,104,101],
    "City":["Hyderabad","Chennai","Bangalore","Chennai","Hyderabad"],
    "Experience":[8,4,3,5,2],
    "Age":[25,30,37,35,25]
}
df = pd.DataFrame(emp_details)
print(df)
df.groupby("City")["Age"].mean()
df.groupby("City")["Age"].min()
df.groupby("City")["Age"].max()
df.groupby("City")["Age"].median()
df.groupby("City")["Age"].count()
df.groupby("City")["Age"].sum()

   EmpID       City  Experience  Age
0    101  Hyderabad           8   25
1    102    Chennai           4   30
2    103  Bangalore           3   37
3    104    Chennai           5   35
4    101  Hyderabad           2   25

City
Bangalore    37
Chennai      65
Hyderabad    50
Name: Age, dtype: int64

In [ ]:
import pandas as pd
data={
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
             "Mumbai", "Chennai", "Bangalore", "Mumbai"],
    "Salary": [30000, 40000, 28000, 50000, 35000, 45000, 25000, 55000]
}
df = pd.DataFrame(data)
print(df)

     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
1   Priya   24    Chennai   40000
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000
6  Vikram   20  Bangalore   25000
7   Meena   27     Mumbai   55000